blank_issues_enabled: false
contact_links:
  - name: Help & support on Discord
    url: https://discord.gg/bmSAZBG
    about: We don't accept support requests on the issue tracker. Please try asking on Discord instead.
  - name: Documentation
    url: https://pmmp.rtfd.io
    about: PocketMine-MP documentation
